### ISSUE TITLE
Provide custom key based on the position in the array.

### ISSUE THREAD

**Issue by donno** [keichi/binary-parser#11]
Hello,

As a result of  #7, it was possible to define the key of an array based on a variable but based on my reading of the code `key` can only be a string as such a function is not supported in this case. 

My goal is ultimately to provide a custom key for based on the position in the array. For example position 0 would be "ExportTable", 1 would be "ImportTable", 2 would be "ResourceTable" and so forth. I imagined I could achieve this if it was possible to define key as a function which knew how many times it was called (thus knowing the index in the array), so it could return a suitable string/name of the element. I suspect in general it would be useful having the key option of a array accept a function would also cover more uses.

My first question is my goal already achievable?

Second question would it be useful if the key option of an array could be a function (like how assert can be a function or a number)?

**Comment by donno** [comment]
Not long after posting this, I came across exactly what I needed. The `formatter` parameter for array can be used to achieve this, by creating a new a new associative array.

So to answer my first question, yes my goal was already achievable.

Sorry for the noise.

**Comment by keichi** [comment]
Hey, sorry I did not reply to your question. Good to hear that you found your solution.
