### ISSUE TITLE
how to create the parser with diagram

### ISSUE THREAD

**Issue by liutaohua** [keichi/binary-parser#114]
in practice，i want who use the system isn't a programer , she just opened a web ,and then we can show any parser with diagram or create it .
so my means is: how to use tree or diagram to show it ?

**Comment by keichi** [comment]
Hi, this package does not provide a direct way to render/visualize a parser.

You could design an AST that represents the structure of a parser, which could probably look like this:

```javascript
[
    {name: "a", type: "uint8"},
    {name: "b", type: "uint16"},
    {name: "x", type: "array", element_type: "uint32", length: 10},
]
```

Your web interface will render an AST and allow users to edit it. Then, you could write a function that translates an AST to a binary-parser's parser object.

**Comment by liutaohua** [comment]
ohhhhh , thanks  so much
