### ISSUE TITLE
support for non-utf8 string (euc-kr)?

### ISSUE THREAD

**Issue by badsaarow** [keichi/binary-parser#127]
This support only utf-8, and ascii.
Is there any workaround for parse euc-kr string?

icvon module can convert between difference encoding.  
Can I use cutom encode instead default string encoding?

**Comment by keichi** [comment]
Hi, the string parser only supports builtin string encodings. Please use the buffer parser and then decode the buffer using iconv. (Maybe you can use the `formatter` option).

**Comment by badsaarow** [comment]
> Hi, the string parser only supports builtin string encodings. Please use the buffer parser and then decode the buffer using iconv. (Maybe you can use the `formatter` option).

Thanks for your advice.

With your help, I can solve my problem as below.

```
  describe('Parser encoder euc-kr', function () {
    const parser = new Parser()
      .buffer('hangul', {
        length: 24,
        formatter: function (enc) {
          return this.$imports.iconv.decode(enc, 'EUC-KR')
        },
        encoder: function (dec) {
          return this.$imports.iconv.encode(dec, 'EUC-KR')
        }
      })

    const dec = {
      hangul: '한글'
    }

    const enc = parser.encode(dec)
    console.log('enc:', enc.toString())
    const decoded = parser.parse(enc)
    console.log('decoded: ', decoded.hangul)
    assert.ok(enc)
  })
```
