### ISSUE TITLE
latest version not published to NPM despite NPM saying v1.4.0

### ISSUE THREAD

**Issue by Zireael** [keichi/binary-parser#129]
Hi,
I see `saveOffset()` is missing in source code. Latest documentation for 1.4.0 reads that skip() was replaced by seek() but this is not correct.
I have `"binary-parser": "^1.4.0"` installed through Yarn/NPM in my project and was getting error that `seek() is not a function`. Renamed to `skip()` and I have working code.

![image](https://user-images.githubusercontent.com/3856578/66708495-00016e00-ed49-11e9-9b55-a4a219414849.png)

Edit: looks like `.saveOffset()` is missing too. Seems that the package published for NPM [https://www.npmjs.com/package/binary-parser](https://www.npmjs.com/package/binary-parser ) is for an older version that is missing several functions mentioned in documentation..

Please push the package to NPM to align documentation with code. Several reported bugs here might have been caused by this issue.

**Comment by keichi** [comment]
Thanks, I haven't released a version that includes #120 and #122 yet. I'll release it as 1.5.0 tomorrow. The README included in the npm package should match the code though. The git tag is also correct: https://github.com/keichi/binary-parser/blob/v1.4.0/README.md

**Comment by keichi** [comment]
@Zireael Just released 1.5.0 that contains all changes in the current master. `seek()` and `saveOffset()` should be available now.

**Comment by keichi** [comment]
Closing, please reopen if you're still seeing this problem.
