### ISSUE TITLE
Align encoder options function documentation

### ISSUE THREAD

**Issue by Gauraden** [keichi/binary-parser#150]
https://www.npmjs.com/package/binary-parser-encoder#setencoderoptionsopts

In the documentation, there is function "setEncoderOptions", but in the example it's "setEncoderOpts".
The main issue is that there are no such functions in the "Parser" object, but it has "encoderSetOptions".
The function name in the documentation should be aligned with code.

**Comment by keichi** [comment]
You are using a [fork](https://github.com/Ericbla/binary-parser) of this package. Please open an issue there.
