### ISSUE TITLE
Trying to instantiate from node-red

### ISSUE THREAD

**Issue by RossWilliamson** [keichi/binary-parser#174]
I'm trying to use the binary-parser in a function from node-red.  In the setup for the function I set the following:

![image](https://user-images.githubusercontent.com/1157036/133172209-13a7b1b9-0925-4948-b1b1-fe784772f6d2.png)

And in the On Message the following:

![image](https://user-images.githubusercontent.com/1157036/133172305-6c2c8119-7105-42ec-a4cb-5c05edc287b6.png)

But I get the following error

"TypeError: Cannot read property 'Parser' of undefined"

I'm sure I'm just doing something wrong but the "require" method does not work

**Comment by keichi** [comment]
Have you installed binary-parser under `~/.node-red`?
```
$ cd ~/.node-red
$ npm install binary-parser
```

**Comment by RossWilliamson** [comment]
> Have you installed binary-parser under `~/.node-red`?
> 
> ```
> $ cd ~/.node-red
> $ npm install binary-parser
> ```

Yes I have - It does the copy from the server as expected

**Comment by keichi** [comment]
Can you try the following? I just tested with Node-RED v2.0.6 and it worked. Btw it seems you don't need to manually install external packages if `functionExternalModules` is set to `true` in your `~/.node-red/settings.json`. Anyway this is not a binary-parser issue.

```javascript
var Parser = binaryParser.Parser;

var parser = new Parser();

return msg;
```
