### ISSUE TITLE
Getting current offset

### ISSUE THREAD

**Issue by oparisy** [keichi/binary-parser#22]
Hi,

is there a way a parser can get access to the current, absolute value of `offset` in the input Buffer? I need it to express a `readUntil` condition.

On a related note: if the provided function for `readUntil` returns `false` when first called, does `array` return an empty array? Or is at least one array entry read before the provided function is called?

Regards.

**Comment by keichi** [comment]
Closing as this should now be possible with `saveOffset()`.
