### ISSUE TITLE
How to use variables and functions that were previously announced

### ISSUE THREAD

**Issue by saper639** [keichi/binary-parser#25]
Hello! Explain how to use variables and functions that were previously announced.
Example:
function test() {
 return 1;
}
var foo = 5;
var myData = new Parser()
        .string('type', {length: 1, formatter: function(arr) {
            console.log(foo);
            console.log(test());
            return arr;
        }});
var buf = new Buffer('2D035958501', 'hex');
console.log(myData.parse(buf));

RefferenceError: foo is not defined
RefferenceError: test is not defined

**Comment by oparisy** [comment]
I could reproduce this behavior here:
https://tonicdev.com/568997e56065940c00b02848/568ab6588ec2e00c00160b3f

I am curious for an explanation, as it is my naive understanding that references to `foo` and `test` should indeed be captured in the closure of the anonymous function.

**Comment by tolmasky** [comment]
This seems to toString the function in question, hence why you are not trapping the closure. Its equivalent to something like this:

test2 = eval(test.toString())
test2() // no access to test1's closures.

The way I know this is that I made a custom toString to test it: https://tonicdev.com/tolmasky/568b78d93901db0d001ac249
