### ISSUE TITLE
Prevent choice nesting

### ISSUE THREAD

**Issue by dolvany** [keichi/binary-parser#28]
Thanks for the great app, but one thing I am wondering. Is it possible to prevent choice from adding a key to the object? Once I get a few choices deep, referencing a value requires something akin to data.a.data.b.data.c. It would be great if there were a way to keep the data structure flatter.

**Comment by shamansir** [comment]
A bit late answer, but you may use formatters for that:

```
.nest('nested', {
    type: someParser,
    formatter: function(v) {
        return v.data;     
    }
});
```

or, use it above this nested parser the same way.

**Comment by keichi** [comment]
Formatters are the recommended way to do this.
