### ISSUE TITLE
Bit field formatter

### ISSUE THREAD

**Issue by Pumpuli** [keichi/binary-parser#29]
You can't use formatters with bitfields other than the last one in a sequence, since the bitfield reading code generation gets deferred until the last one, but the formatter code is inserted after each field in a sequence. Thus all the other bit field values get overwritten when the actual reading and bit shifting code is executed, because the formatters were called earlier.

**EDIT:**

It's been almost five years, but I thought I'd add a concrete example. 😄 I'm using `binary-parser@1.6.2` for these.

Here's a simple parser that parses uint8 values, and uses formatter for those (although these formatters just return a constant string).

```js
new Parser()
    .uint8('a', { formatter: () => 'first' })
    .uint8('b', { formatter: () => 'second' })
    .uint8('c', { formatter: () => 'third' });
```

The generated code is fine. First we read the value to the `vars` and then we immediately replace that value with the formatted version.

```js
vars.a = dataView.getUint8(offset, false);
offset += 1;
vars.a = (() => 'first').call(this, vars.a);

vars.b = dataView.getUint8(offset, false);
offset += 1;
vars.b = (() => 'second').call(this, vars.b);

vars.c = dataView.getUint8(offset, false);
offset += 1;
vars.c = (() => 'third').call(this, vars.b);
```

Here's the same thing, except we're parsing bitfields. We're still using formatters.

```js
new Parser()
    .bit8('a', { formatter: () => 'first' })
    .bit8('b', { formatter: () => 'second' })
    .bit8('c', { formatter: () => 'third' });
```

Now there's a bug in the generated code:

```js
vars.a = (() => 'first').call(this, vars.a);  // Formatter called with vars.a being undefined
vars.b = (() => 'second').call(this, vars.b); // Same with vars.b
var $tmp1 = dataView.getUint16(offset);
var $tmp2 = dataView.getUint8(offset + 2);
var $tmp0 = ($tmp1 << 8) | $tmp2;
offset += 3;
vars.a = $tmp0 >> 16 & 255; // The values are finally parsed
vars.b = $tmp0 >> 8 & 255;
vars.c = $tmp0 >> 0 & 255;
vars.c = (() => 'third').call(this, vars.c); // But only the last one is properly formatted
```

When parsing multiple successive bitfields, the code that populates the varibles is "deferred" to the end. However, the code that calls the formatters is not deferred. Thus the formatters get called too early, when the values don't exist yet.

The "deferring" feature here causes the issue. Or rather the lack of deferring for the formatters. The bitfield parsing code is only generated [when there are no more bitfields](https://github.com/keichi/binary-parser/blob/06701a0ba05cfa92a17b826a234f22cb8bfcb1dd/lib/binary_parser.ts#L857-L904) in the succession. But the code that calls the formatters is generated [every time](https://github.com/keichi/binary-parser/blob/06701a0ba05cfa92a17b826a234f22cb8bfcb1dd/lib/binary_parser.ts#L806-L808).

**Comment by wang701** [comment]
:+1:

**Comment by kaYcee** [comment]
Can functoid's patch please be merged with the main repository (and eventually be made available through npm)? Thanks!

**Comment by jayeheffernan** [comment]
This is a problem for me too.  E.g.:

```
new Parser()
    .bit1('first', { formatter: val => !!val } )
    .bit1('second', { formatter: val => !!val })
    .getCode()
```

The formatter for `first` is called before`first` and `second` are read (then finally the formatter for `second` is called.  The result is that `second` is a boolean but `first` is an integer.
