### ISSUE TITLE
Access prior parsed values in Array formatter

### ISSUE THREAD

**Issue by dsshap** [keichi/binary-parser#30]
I have this example:

```
var payload = Parser.start()
        .uint8('data_type')
        .uint8('data_length')
        .array('data', {
          type: 'uint8',
          length: 'data_length',
          formatter: function(array){
            // ACCESS 'data_type' HERE!!
            return array
          }
        })
```

I want to be able to access data_type inside formatter of array.

I inspected `this`, but it wasn't clear how to get to this value.
The scope is available in `length'.

Is this possible? If yes, how?

**Comment by p0358** [comment]
In case it helps someone coming here from a search, look in #75 comments

**Comment by keichi** [comment]
Please try using `$parent` and `$root` introduced in #166.
