### ISSUE TITLE
Defining 'assert' and 'formatter' functions externally

### ISSUE THREAD

**Issue by kevinryan** [keichi/binary-parser#33]
First let me say that this parser is great and easy to use - thanks!

However, given a defined function:

<pre><code>
    function range (min, max) {
        return function(x) {
        return min <= x && x <= max;
        };
    }
</code></pre>

I would like to create a parser like this to use my 'range' function.

<pre><code>
var dataParser = new Parser()
    .endianess('little')
    .uint8('inside_humidity', {assert: range(0, 100)})
    .uint16('barometer', {assert: range(20000, 32500),
            formatter: function(x) {return x/1000;}})
    .uint16('wind_direction', {assert: range(0, 360)})
    .uint16('crc');
</code></pre>

But this does not work -- and according to: [http://stackoverflow.com/questions/37597883/javascript-using-non-inline-function](url) the reason is because you 'stringify the function'.

Because of that, if we want to use named functions for asserts and formatters we have to use a work-around like this:

<pre><code>
function range (min, max) {
    return new Function("x", "return " + JSON.stringify(min) +
            " <= x && x <=  " + JSON.stringify(max)+ ";");
}
</code></pre>

Is this something you'd be interested in changing so the use of named 'assert' and 'formatter' functions will be more straightforward?

Thanks,
Kevin Ryan

**Comment by NuSkooler** [comment]
Very interested in something for this. I'm in the process of replacing the old `binary` module with this one (which rocks BTW!), but the lack of the ability to use my own functions easily makes some work very cumbersome.

**Comment by Simran-B** [comment]
Could own functions be injected perhaps? Something along `new Parser( [range] )`?

**Comment by p0358** [comment]
Here's what I did in my use-case:
```js
let outside = /* JS array of strings here */;
let formatter = (function formatter(i) { return outside[i] || i; });
let formatterstr = formatter.toString().replace("outside", JSON.stringify(outside));

parser = parser.uint8(name, {
    formatter: new Function("x", "return (" + formatterstr + ")(x)"),
});
```
it would be equivalent of doing:
```js
parser = parser.uint8(name, {
    formatter: item => outside[i] || i
});
```

**Comment by gnarea** [comment]
I was going to raise a related issue but I won't because I think its root cause is the same as this one: binary-parser generates JS code that gets `eval`ed, so that has profound implications on what you can do in an `assert` or `formatter`.

In my case I wasn't using external values at all. My formatter was simply `(value) => value.readUIntLE(0, 3)`. But because I'm using TypeScript, I got some pretty unhelpful errors like `cov_1ux0jwh81w is not defined`.

I think there should be a big warning about this.

@p0358's workaround worked for me, although I really wish I didn't have to do that:

```
{
  formatter: new Function('buf', 'return buf.readUIntLE(0, 3)'),
}
```
