### ISSUE TITLE
Running Istanbul on a formatter function parser failed the test

### ISSUE THREAD

**Issue by chenfli** [keichi/binary-parser#34]
Hi,
The Binary Parser is great and works flawless, however when I run istanbull over mocha to test my parsing I get a wierd errors.

My Parsers are inside an Object like this:

```

function aParser(client) {
    var self=this;
    var BinParser = require('binary-parser').Parser;
     self.eventReportParser =  new BinParser()
        .endianess('big')
        .uint32('UpdateTime')
        .uint32('TimeofFix')
        .int32('Latitude', {formatter: function(x) { return x /10000000;}})
        .int32('Longitude', {formatter: function(x) { return x /10000000;}});

 self.calampHeaderParser = new BinParser()
        .endianess('big')
        .uint8('OptionsByte')
        .uint8('ServiceType')
        .uint8('MessageType')
        .uint16('Sequence')
        .choice('data', {
            tag: 'MessageType',
            choices: {      
                2: self.eventReportParser,
                 }
        });   
}
// Usage is as follows:
aParser.prototype.parse = function (message) {
    var msg;
    try {
        msg = this.calampHeaderParser.parse(message);
    } catch (e) {
 }
```

This works fine, and test works fine when running mocha only.

However, when I am running istanbul

./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- --recursive -R xunit-file -r should 

I got execptions only on parsers with function inside,
Any idea why ?

Thanks in advance

**Comment by tudro** [comment]
Hi, same for me. I get errors like:
`ReferenceError: cov_3qe7o26op is not defined

at Object.eval (eval at <anonymous> (node_modules\binary-parser\lib\binary_parser.js:286:21), <anonymous>:11:23)

at Parser.eval [as compiled] (eval at <anonymous> (node_modules\binary-parser\lib\binary_parser.js:286:21), <anonymous>:11:91)

at Parser.parse (node_modules\binary-parser\lib\binary_parser.js:337:17)
`
Thank you

**Comment by danperetz** [comment]
Hi,
We also encounter this issue. Any news?

**Comment by macbutch** [comment]
Anyone have any suggestions for this? This seems to be an issue only for buffers (for me, so far). I'm able to "work around" this by telling instanbul to ignore some lines:

```
/* istanbul ignore next */
const parser = new Parser()
  // ...
  .buffer('payload', {
    length: function () {
      return this.length
    }
  })
```

Using the parser doesn't seem to be a problem and it's not a problem in all cases (like I said, only for buffers so far).

**Comment by cmdcolin** [comment]
I don't know the exact reason for this but it's due to code generation and eval of the formatter functions. I think you just have to skip it with that istanbul ignore next.

**Comment by keichi** [comment]
We've migrated to nyc.
