### ISSUE TITLE
Binary parser missing

### ISSUE THREAD

**Issue by Bilarr** [keichi/binary-parser#48]
Greetings! 
It is probably silly by me but I really couldn't find a solution for that...
I recently downloaded npm and when I tried to use 'npm install' on webstorm it first told me that 'binary-parser' is missing.
I checked online and found out that I should use 'npm install binary-parser' and so I did.
Now when I try to run 'npm install' it says that the binary-parser isn't located in the npm registery.
I couldn't find a solution for it...is there any way that you can help me?

**Comment by keichi** [comment]
Hi! I'm not sure if that problem is specific to binary-parser...
On my environment with the latest npm (5.3.0), I can successfully install binary-parser. Also, I've confirmed that the package is published on the npm registry. Maybe your problem has something to do with Webstorm?

**Comment by Bilarr** [comment]
My problem is already solved.
I exidently typed binary-perser instead of binary-parser.
Thanks anyway !

2017-08-21 9:20 GMT+03:00 Keichi Takahashi <notifications@github.com>:
