### ISSUE TITLE
Buffer is not defined on generated code calling compiled

### ISSUE THREAD

**Issue by dror1544** [keichi/binary-parser#60]
I am trying to use Parser in Angular 5 (using @types/binary-parser). 
In order to test the module first I use the IP header example. 
when doing that I get the following error 

> ERROR ReferenceError: Buffer is not defined
    at Parser.eval [as compiled] (eval at Parser.compile (webpack-internal:///../../../../binary-parser/lib/binary_parser.js), <anonymous>:3:1)
    at Parser.parse (webpack-internal:///../../../../binary-parser/lib/binary_parser.js:337)
    at AppComponent.parse (webpack-internal:///../../../../../src/app/app.component.ts:47)
    at AppComponent.ngOnInit (webpack-internal:///../../../../../src/app/app.component.ts:21)
    at checkAndUpdateDirectiveInline (webpack-internal:///../../../core/esm5/core.js:12596)
    at checkAndUpdateNodeInline (webpack-internal:///../../../core/esm5/core.js:14123)
    at checkAndUpdateNode (webpack-internal:///../../../core/esm5/core.js:14066)
    at debugCheckAndUpdateNode (webpack-internal:///../../../core/esm5/core.js:14959)
    at debugCheckDirectivesFn (webpack-internal:///../../../core/esm5/core.js:14900)
    at Object.eval [as updateDirectives] (ng:///AppModule/AppComponent_Host.ngfactory.js:8)

If I call Buffer,isBuffer(buf) on my code before calling .parse() it works just fine. I removed this piece of code from binary_parser.js in function getCode and the generated code works fine.
 It seems that I am missing something in the declaration of Buffer. It is included in my app.Module. so I can not put the finger on what am I missing?
 This is my code as I used it:

`import { Parser } from 'binary-parser';
import { Component } from '@angular/core';
import { OnInit } from '@angular/core/src/metadata/lifecycle_hooks';
import { Buffer } from 'buffer';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit{
  
  title = 'app';

  ngOnInit(): void {
    this.parse()
  }
  parse(){

    let ipHeader = new Parser()
    .endianess('big')
    .bit4('version')
    .bit4('headerLength')
    .uint8('tos')
    .uint16('packetLength')
    .uint16('id')
    .bit3('offset')
    .bit13('fragOffset')
    .uint8('ttl')
    .uint8('protocol')
    .uint16('checksum')
    .array('src', {
        type: 'uint8',
        length: 4
    })
    .array('dst', {
        type: 'uint8',
        length: 4
    });

    const buf = new Buffer('450002c5939900002c06ef98adc24f6c850186d1', 'hex');
    Buffer.isBuffer(buf);
   // Parse buffer and show result
   console.log(ipHeader.parse(buf));
  }

}`

**Comment by jordicenzano** [comment]
+1

**Comment by riggs** [comment]
`Buffer` needs to be defined globally (e.g. on `window`) at runtime because binary-parser creates code and calls it with `eval`.

**Comment by jordicenzano** [comment]
Fixed with a workaround :-(

Using grunt:
```
'string-replace': {
            dist: {
                files: {
                    './dist/js/ABC.js': './dist/js/ABC.js'
                },
                options: {
                    replacements: [{
                        pattern: 'if (!Buffer.isBuffer(buffer)) {',
                        replacement: 'if (false) {'
                    }]
                }
            }
        },
```

I know is not very elegant, but it does the trick

**Comment by dror1544** [comment]
@riggs did not understand where to define the buffer.
Currently as a workaround I removed the check of isBuffer from the code but I am looking for something more elegant

`
Parser.prototype.getCode = function() {
    var ctx = new Context();
 
    // ctx.pushCode('if (!Buffer.isBuffer(buffer)) {');
    // ctx.generateError('"argument buffer is not a Buffer object"');
    // ctx.pushCode('}');

    if (!this.alias) {
        this.addRawCode(ctx);
    } else {
        this.addAliasedCode(ctx);`

**Comment by IAmPicard** [comment]
Has anyone figured out a cleaner solution for this? I too manually comment out those 3 lines, but whenever I set up a new enlistment I need to remember doing it again.
Plus, new folks working on my project also need to know about it.

FWIW, I'm in a browser environment (Electron or Cordova) and need to polyfill Buffer (which works perfectly fine after commenting out those lines).

**Comment by Xample** [comment]
The code is ran at line [322](https://github.com/keichi/binary-parser/blob/master/lib/binary_parser.js#L322)
 within ```this``` context, we just need to import and provide the Buffer object in another context.
`var Buffer = require("buffer").Buffer;
`
`  this.compiled = vm.runInNewContext(src,{Buffer});
`
I will open a pull request
