### ISSUE TITLE
No longer works in browser environment after 1.3.2

### ISSUE THREAD

**Issue by IAmPicard** [keichi/binary-parser#70]
It looks like with 3d7cb5728cfcb064dad1e2d3cea98aa8ceade56e you switched from using a plain Function() constructor to using the Node "vm" module for evaluation. Since "vm" is not available in browser environments (such as Electron or plain browser-ified code) it will no longer work there.

There are vm polyfills for browsers like [this](https://github.com/dfkaye/vm-shim), but not sure how those fit into your bigger plans. Is browser environment something you care about?

Thanks!

**Comment by Simran-B** [comment]
I guess the question is what the reason was to switch to vm module. Probably security? It could be made optional I guess, to be configurable with some option like `new Parser( {sandboxed: false} )`?

**Comment by James-Firth** [comment]
I'd also like to be able to use this in-browser

**Comment by IAmPicard** [comment]
FWIW, I added a Buffer polyfill and got rid of those 3 lines of code [here](https://github.com/keichi/binary-parser/blob/e6d19cb208a72e08ba2b8dd2ac603c3ca67628ca/lib/binary_parser.js#L256), and I can use it in a browser environment.

**Comment by keichi** [comment]
This was fixed in #103 and #121.
