### ISSUE TITLE
Why no uint24?

### ISSUE THREAD

**Issue by fxp** [keichi/binary-parser#83]
I found some other parsers have uint24 type, why not in binary-parser?

**Comment by Adondriel** [comment]
You _should_ be able to use bit[1-32](name[, options]) as an alternative?

**Comment by South-Paw** [comment]
Doesn't really hold up to use bit24 when you need two in sequence and binary-parser errors with

`Currently, bit field sequence longer than 4-bytes is not supported.`

So why is there no `int24`? 😟

**Comment by nickdaugherty** [comment]
See #93 for a workaround.

**Comment by yuhr** [comment]
Closing because of duplicate.
